name: Poly_Collision
description: Polygon collision plugin using Separated Axis Theorem.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: